default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['FINAL_CAPSTONE_DATABASE_USERNAME'] %>
  password: <%= ENV['FINAL_CAPSTONE_DATABASE_PASSWORD'] %>
  # port: 5433

development:
  <<: *default
  database: pss-digital-development

test:
  <<: *default
  database: pss-digital-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: pss-digital-production
  username: pss-digital
  password: <%= ENV['FINAL_CAPSTONE_DATABASE_PASSWORD'] %>
